// application-client/openvidu-react/src/components/VideoComponent.tsx
import { LocalVideoTrack, RemoteVideoTrack } from "livekit-client";
import "./VideoComponent.css";
import { useEffect, useRef } from "react";

interface VideoComponentProps {
    track: LocalVideoTrack | RemoteVideoTrack;
    participantIdentity: string;
    local?: boolean;
}

function VideoComponent({ track, participantIdentity, local = false }: VideoComponentProps) {
    const videoElement = useRef<HTMLVideoElement | null>(null);

    useEffect(() => {
        if (videoElement.current) {
            track.attach(videoElement.current);
        }

        return () => {
            track.detach();
        };
    }, [track]);

    return (
        <div id={"camera-" + participantIdentity} className="video-container">
            <div className="participant-data">
                <p>{participantIdentity + (local ? " (You)" : "")}</p>
            </div>
            <video ref={videoElement} id={track.sid}></video>
        </div>
    );
}

export default VideoComponent;

// basic/frontend/angular/src/app/video/video.component.ts
import { Component, ElementRef, Input, ViewChild } from '@angular/core';
import { LocalVideoTrack, RemoteVideoTrack } from 'livekit-client';

@Component({
    selector: 'video-component',
    standalone: true,
    imports: [],
    templateUrl: './video.component.html',
    styleUrl: './video.component.css',
})
export class VideoComponent {
    @ViewChild('videoElement') videoElement?: ElementRef<HTMLVideoElement>;

    private _track?: LocalVideoTrack | RemoteVideoTrack;
    @Input() participantIdentity?: string;
    @Input() isLocal = false;

    ngAfterViewInit() {
        if (this._track && this.videoElement) {
            this._track.attach(this.videoElement.nativeElement);
        }
    }

    @Input()
    set track(track: LocalVideoTrack | RemoteVideoTrack) {
        this._track = track;

        if (this.videoElement) {
            this._track.attach(this.videoElement.nativeElement);
        }
    }
}

<div id="camera-{{ participantIdentity }}" class="video-container">
    <div class="participant-data">
        <p>{{ participantIdentity }} @if (isLocal) { (You)}</p>
    </div>
    <video #videoElement></video>
</div>
