// application-client/openvidu-react/src/components/AudioComponent.tsx
import { LocalAudioTrack, RemoteAudioTrack } from "livekit-client";
import { useEffect, useRef } from "react";

interface AudioComponentProps {
    track: LocalAudioTrack | RemoteAudioTrack;
}

function AudioComponent({ track }: AudioComponentProps) {
    const audioElement = useRef<HTMLAudioElement | null>(null);

    useEffect(() => {
        if (audioElement.current) {
            track.attach(audioElement.current);
        }

        return () => {
            track.detach();
        };
    }, [track]);

    return <audio ref={audioElement} id={track.sid} />;
}

export default AudioComponent;

// application-client/openvidu-vue/src/components/AudioComponent.vue
<script setup lang="ts">
import { LocalAudioTrack, RemoteAudioTrack } from 'livekit-client';
import { onMounted, onUnmounted, ref } from 'vue';

const props = defineProps<{
    track: LocalAudioTrack | RemoteAudioTrack;
}>();
const audioElement = ref<HTMLMediaElement | null>(null);

onMounted(() => {
    if (audioElement.value) {
        props.track.attach(audioElement.value);
    }
});

onUnmounted(() => {
    props.track.detach();
});
</script>

<template>
    <audio ref="audioElement" :id="track.sid"></audio>
</template>
